[phases.setup]
nixPkgs = [
    'php82',
    'php82Packages.composer'
]

[phases.install]
cmds = [
    'composer install --no-dev',
    'echo "APP_NAME=Laravel\nAPP_ENV=production\nAPP_DEBUG=false\nAPP_URL=https://laravel-ecommerceplatform-production.up.railway.app\nLOG_CHANNEL=stack\nBROADCAST_DRIVER=log\nCACHE_DRIVER=file\nFILESYSTEM_DISK=local\nQUEUE_CONNECTION=sync\nSESSION_DRIVER=file\nSESSION_LIFETIME=120\nDB_CONNECTION=mysql" > .env',
    'php artisan key:generate --force',
    'php artisan config:cache',
    'php artisan route:cache'
]

[phases.build]
cmds = [
    'php artisan storage:link'
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[deploy]
startCommand = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT' 