[build]
builder = "nixpacks"
buildCommand = "curl -sS https://getcomposer.org/installer | php && php composer.phar install --no-dev"

[deploy]
startCommand = "php artisan serve --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 